### PR TITLE
Fix clippy lint

### PR DESCRIPTION
**Pull request by pentamassiv**
"forbid" should be replaced with "deny"

### CODE REVIEW

**Review by notgull — CHANGES_REQUESTED** [review]
We can set `deny` for `rust_2018_idioms`, but `forbid(unsafe_code)` makes this crate show up as clean in unsafe code analysis tools.

**Comment by notgull** [comment]
What is this lint breaking, exactly?

**Comment by pentamassiv** [comment]
The warning is very confusing. If you have a look at [this Action](https://github.com/rust-windowing/xkeysym/actions/runs/6605788320/job/17941324453) and unfold the step "Run clippy", you will see a bunch of similar errors to this:

```
    Checking xkeysym v0.2.0 (/home/runner/work/xkeysym/xkeysym)
warning: allow(unused_extern_crates) incompatible with previous forbid
  --> src/lib.rs:44:38
   |
27 | #![forbid(unsafe_code, rust_2018_idioms)]
   |                        ---------------- `forbid` level set here
...
44 | #[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
   |                                      ^^^^^^^^^^^^^^^^ overruled by previous forbid
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #81670 <https://github.com/rust-lang/rust/issues/81670>
   = note: `#[warn(forbidden_lint_groups)]` on by default
   = note: this warning originates in the derive macro `serde::Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```
In the linked issue, they recommend changing the lint level from forbid to deny.

**Review by notgull — APPROVED** [review]
Okay, thanks for clarifying!

**Pull request merged**
